# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32ec94111446010e7f656b15b301cb94c99a216583e0ec6be574c64eae4a244563a020ce762a366e7d800d2e74fd55272c9e280e3482aa478eca9a50b0dbd09f

test:
  secret_key_base: 3fecfeb1db87dc7517944f4fd6ce2350d70b2d6d6e97b988f71f0817ff8d059d1133489faec365eddd92f55e4ee361d9b5e08f221b5cd1f76980b88f5d46760b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
